version: 2.1

jobs:
#job name is build
  build:
  #environment(docker) in which python code will get run
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build